react-webpack:
   image: "registry.it.kmitl.ac.th/react-webpack"
   container_name: "react-webpack"
   hostname: "react-webpack"
   restart: "always"
   ports:
     - "3000:3000"
   external_links:
     - "mongodb"
